name: Deploy AMSG Desde Cero

on:
  push:
    branches: "quintoa"

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ghcr.miguesaint/amsgdecero:1.0.0

    - name: Mostrar variables basicas
    - run:
        echo "Probando conexion SSH con:"
        echo "Host: ${{ secrets.VPS_HOST }}"
        echo "Usuario: ${{ secrets.VPS_USER }}"
        echo "Puerto: ${{ secrets.VPS_SSH_PORT }}"
        echo "Password: ${{ secrets.VPS_PASSWORD }}"

    - name:  Deploy con eliminacion del stack
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_SSH_PORT }}
        script:
          echo "Conexion con ¡ÉXITO! desde Github Actions"
          hostname
          whoami
          uptime
          
      